title: Gurumoorthi
logo: /assets/img/DP.png
description: Threat Researcher with 4+ years of experience in the security industry. Specializes in research of emerging threats, surfing in darkweb, and develop effective automation systems for threat detection and protection. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
