title: <center><a href="./another-page.html">Gurumoorthi</a></center>
logo: /assets/img/DP.png
description: <center> Threat Researcher | AI </center>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
